#!/usr/bin/env bash
# Install the agent units on this host. Idempotent.
#
#   sudo bash deploy/install.sh
#   sudo systemctl enable --now vertex-agent@{ble,wifi,bridge}
#
# Reads /etc/default/vertex-agent -- the only per-host file -- and generates the
# drop-in holding the directives that cannot reference environment variables.
set -euo pipefail
[ "$(id -u)" -eq 0 ] || { echo "run as root" >&2; exit 1; }
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
UNITS=/etc/systemd/system

install -D -m644 "$HERE/vertex-agent@.service" "$UNITS/vertex-agent@.service"
install -D -m644 "$HERE/vertex-agent@bridge.service.d/capabilities.conf" \
    "$UNITS/vertex-agent@bridge.service.d/capabilities.conf"

if [ -f /etc/default/vertex-agent ]; then
    echo "keeping existing /etc/default/vertex-agent"
else
    install -D -m644 "$HERE/vertex-agent.env" /etc/default/vertex-agent
    echo "wrote /etc/default/vertex-agent -- EDIT IT, then re-run this script"
fi

# shellcheck disable=SC1091
. /etc/default/vertex-agent
: "${VERTEX_USER:?set VERTEX_USER in /etc/default/vertex-agent}"
: "${VERTEX_REPO:?set VERTEX_REPO}"
: "${VERTEX_DATA:?set VERTEX_DATA}"
[ -d "$VERTEX_REPO/vertex" ] || { echo "VERTEX_REPO=$VERTEX_REPO is not the repo" >&2; exit 1; }
: "${VERTEX_PYTHON:=/usr/bin/python3}"
[ -x "$VERTEX_PYTHON" ] || { echo "VERTEX_PYTHON=$VERTEX_PYTHON is not executable" >&2; exit 1; }
# The dependency check preflight does, before enabling a unit that would only fail
# at start with ModuleNotFoundError in the journal.
if ! (cd "$VERTEX_REPO" && "$VERTEX_PYTHON" -c 'import vertex.agent.__main__') 2>/dev/null; then
    echo "error: $VERTEX_PYTHON cannot import vertex.agent" >&2
    echo "       fix: cd $VERTEX_REPO && $VERTEX_PYTHON -m pip install -e ." >&2
    exit 1
fi

# User=, WorkingDirectory= and ReadWritePaths= do not expand ${VAR}: only
# ExecStart= does. Generated here as literals instead.
install -d -m755 "$UNITS/vertex-agent@.service.d"
cat >"$UNITS/vertex-agent@.service.d/host.conf" <<CONF
# Generated by deploy/install.sh from /etc/default/vertex-agent. Do not edit --
# change that file and re-run the installer.
#
# These four cannot live in the template: User=, WorkingDirectory= and
# ReadWritePaths= take literals rather than \${VAR}, and ExecStart= expands
# variables in its arguments but not in the executable position. See the template's
# header for why a symlink is not a way around the last one.
[Service]
User=$VERTEX_USER
WorkingDirectory=$VERTEX_REPO
ReadWritePaths=$VERTEX_DATA
ExecStart=
ExecStart=$VERTEX_PYTHON -u -m vertex.agent --type %i --data-dir $VERTEX_DATA --interface $VERTEX_IFACE --serial $VERTEX_SERIAL
CONF
echo "wrote $UNITS/vertex-agent@.service.d/host.conf"

# The ble agent needs the serial port; dialout grants it without root.
if id -nG "$VERTEX_USER" | grep -qw dialout; then
    echo "$VERTEX_USER already in dialout"
else
    usermod -aG dialout "$VERTEX_USER"
    echo "added $VERTEX_USER to dialout -- the ble agent needs a re-login or reboot"
fi
install -d -o "$VERTEX_USER" -m755 "$VERTEX_DATA"

systemctl daemon-reload
echo
for t in ble wifi bridge; do
    systemd-analyze verify "vertex-agent@$t.service" 2>&1 |
        grep -v '^/etc/systemd/system/[^v]' | sed "s/^/  verify($t): /" || true
done
echo
echo "next:"
echo "  sudo systemctl enable --now vertex-agent@{ble,wifi,bridge}"
echo "  systemctl status 'vertex-agent@*'"
